### ISSUE TITLE
SQL is using literal string comparison instead of boolean compare

### ISSUE THREAD

**Issue by TinLe** [cloudquery-policies/gcp#19]
### Describe the bug

The SQL statement is looking for string 'true' but GCP accepts 'TRUE' and variations, e.g. 'True' also work.  This leads to project failing this policy due to not matching string 'true'.

### Expected Behavior

Should work with all variation of casing for boolean value 'true'.

### Steps to Reproduce

Run policy against projects with oslogin-enabled set to non lower cased 'true'

### Possible Solution

Use boolean comparison instead of string compare.

Alternative is to ignore case when comparing.

### Provider and CloudQuery version

CQ: v0.22.10; GCP provider v0.7.1-linux_amd64

**Comment by erezrokah** [comment]
Thank you for reporting the issue @TinLe, this is a great catch 👍 

To clarify, you're referring to this specific query https://github.com/cloudquery-policies/gcp/blob/6bcbeeeccd095f1323aa8fb511f39c5a185cca14/queries/compute/oslogin_disabled.sql#L5 correct?

Any other queries you'd like to see this change?

For boolean fields we might want to keep boolean comparison, but for string fields that represent a condition I agree we might want to do a case insensitive comparison.

Please let me know what you think.

Also, if you'd like to contribute this fix please let us know (and if not that's totally cool too, and we will implement a fix once we confirm the desired behavior)

**Comment by TinLe** [comment]
@erezrokah Yes, that line.  I believe there are also other similar comparisons in the policies.  This particular line was the one that I tripped on, as we have projects using variation of 'true' and many start showing as failed.

A quick search of this repo show one other place where string comparison to 'true' is being done.

https://github.com/cloudquery-policies/gcp/search?q=true

For example:
https://github.com/cloudquery-policies/gcp/blob/7626759e5aa81d4a82d6f312467ada02dc273971/queries/compute/serial_port_connection_enabled.sql#L4

**Comment by erezrokah** [comment]
Thanks for the follow up @TinLe, very useful 🚀  I'll share this with the team

**Comment by erezrokah** [comment]
Hi @TinLe and sorry for the delay. I tested the supported variants and submitted a fix for this issue https://github.com/cloudquery-policies/gcp/pull/24
